version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - AUTH_URL=nginx
      - AUTH_PORT=80
  auth:
    depends_on:
      - auth_mongo
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./auth:/app
    environment:
      - NODE_ENV=development
      - AUTH_PORT=3000
      - COOKIE_KEY_1=key_1
      - COOKIE_KEY_2=key_2
      - AUTH_MONGO_URL=auth_mongo
      - AUTH_MONGO_PORT=27017
      - JWT_KEY=jwt_key
      - JWT_EXPIRATION_TIME=30
  tickets:
    depends_on:
      - tickets_mongo
    build:
      context: ./tickets
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./tickets:/app
    environment:
      - NODE_ENV=development
      - TICKETS_PORT=3000
      - COOKIE_KEY_1=key_1
      - COOKIE_KEY_2=key_2
      - TICKETS_MONGO_URL=tickets_mongo
      - TICKETS_MONGO_PORT=27017
      - JWT_KEY=jwt_key
      - JWT_EXPIRATION_TIME=30
  auth_mongo:
    image: "mongo:latest"
  tickets_mongo:
    image: "mongo:latest"
  nginx:
    restart: always
    depends_on:
      - client
      - auth
      - auth_mongo
      - tickets_mongo
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
