version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - AUTH_URL=nginx
      - AUTH_PORT=80
  nats:
    image: "nats-streaming:latest"
    command:
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-hbi"
      - "5s"
      - "-hbt"
      - "5s"
      - "-hbf"
      - "2"
      - "-SD"
      - "-cid"
      - "ticketing"
    ports:
      - 4222:4222
      - 8222:8222
  auth:
    depends_on:
      - auth_mongo
      - nats
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./auth:/app
    environment:
      - NODE_ENV=development
      - AUTH_PORT=3000
      - COOKIE_KEY_1=key_1
      - COOKIE_KEY_2=key_2
      - AUTH_MONGO_URL=auth_mongo
      - AUTH_MONGO_PORT=27017
      - JWT_KEY=jwt_key
      - JWT_EXPIRATION_TIME=30
  tickets:
    depends_on:
      - tickets_mongo
      - nats
    build:
      context: ./tickets
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./tickets:/app
    environment:
      - NODE_ENV=development
      - TICKETS_PORT=3000
      - TICKETS_MONGO_URL=tickets_mongo
      - TICKETS_MONGO_PORT=27017
      - COOKIE_KEY_1=key_1
      - COOKIE_KEY_2=key_2
      - JWT_KEY=jwt_key
      - JWT_EXPIRATION_TIME=30
      - NATS_CLUSTER_ID=ticketing
      - NATS_URL=http://nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=
  orders:
    depends_on:
      - orders_mongo
      - nats
    build:
      context: ./orders
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./orders:/app
    environment:
      - NODE_ENV=development
      - ORDERS_PORT=3000
      - ORDERS_MONGO_URL=orders_mongo
      - ORDERS_MONGO_PORT=27017
      - COOKIE_KEY_1=key_1
      - COOKIE_KEY_2=key_2
      - JWT_KEY=jwt_key
      - JWT_EXPIRATION_TIME=30
      - NATS_CLUSTER_ID=ticketing
      - NATS_URL=http://nats
      - NATS_PORT=4222
      - NATS_CLIENT_ID=
  auth_mongo:
    image: "mongo:latest"
  tickets_mongo:
    image: "mongo:latest"
  orders_mongo:
    image: "mongo:latest"
  nginx:
    restart: always
    depends_on:
      - client
      - auth
      - auth_mongo
      - tickets
      - tickets_mongo
      - orders
      - orders_mongo
      - nats
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
