apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: docker.io/denyslins/ticketing-auth
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: NODE_ENV
            - name: AUTH_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: AUTH_PORT
            - name: COOKIE_KEY_1
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: COOKIE_KEY_1
            - name: COOKIE_KEY_2
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: COOKIE_KEY_2
            - name: AUTH_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: AUTH_MONGO_URL
            - name: AUTH_MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: AUTH_MONGO_PORT
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: JWT_KEY
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-hcm7h9574t
                  key: JWT_EXPIRATION_TIME
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
