apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: docker.io/denyslins/ticketing-client
          env:
            - name: AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: AUTH_URL
            - name: AUTH_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: AUTH_PORT
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: client-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
