apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: docker.io/denyslins/ticketing-orders
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: NODE_ENV
            - name: ORDERS_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: ORDERS_PORT
            - name: ORDERS_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: ORDERS_MONGO_URL
            - name: ORDERS_MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: ORDERS_MONGO_PORT
            - name: COOKIE_KEY_1
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: COOKIE_KEY_1
            - name: COOKIE_KEY_2
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: COOKIE_KEY_2
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: JWT_KEY
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: JWT_EXPIRATION_TIME
            - name: NATS_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: NATS_CLUSTER_ID
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: NATS_URL
            - name: NATS_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-mgb5tkt48c
                  key: NATS_PORT
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: orders-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000
