apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: docker.io/denyslins/tickets-tickets
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: NODE_ENV
            - name: TICKETS_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: TICKETS_PORT
            - name: COOKIE_KEY_1
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: COOKIE_KEY_1
            - name: COOKIE_KEY_2
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: COOKIE_KEY_2
            - name: TICKETS_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: TICKETS_MONGO_URL
            - name: TICKETS_MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: TICKETS_MONGO_PORT
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: JWT_KEY
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: tickets-secret-48cg77dbmk
                  key: JWT_EXPIRATION_TIME
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
